# https://taskfile.dev

version: '3'

vars:
  PLUGIN_VERSION: 0.3.1
  OUTPUT_FILENAME: terraform-provider-ceph
  LDFLAGS: -X main.version=$(git describe --always --abbrev=40 --dirty)
  #TAGS: -tags luminous
  TAGS:

tasks:
  default:
    cmds:
      - task --list
    silent: true

  build:
    desc: Build the plugin into current folder.
    cmds:
      - echo "Building {{.OUTPUT_FILENAME}}"
      - go mod tidy
      - go fmt ./ceph .
      - go run golang.org/x/lint/golint -set_exit_status ./ceph .
      - go vet {{.TAGS}} ./ceph
      - go build {{.TAGS}} -ldflags "{{.LDFLAGS}}" -o "{{.OUTPUT_FILENAME}}"
      - echo "Done!"
    silent: true

  install:
    desc: Build and install the plugin in the correct folder (resolved automatically based on current Operating System).
    vars: 
      WINDOWS_OUTPUT_PATH: '{{.APPDATA}}\HashiCorp\Terraform\plugins\registry.terraform.io\provider\ceph\{{.PLUGIN_VERSION}}\{{OS}}_{{ARCH}}\{{.OUTPUT_FILENAME}}'
      DARWIN_OUTPUT_PATH: '{{.HOME}}/Library/Application Support/io.terraform/plugins/registry.terraform.io/provider/ceph/{{.PLUGIN_VERSION}}/{{OS}}_{{ARCH}}/{{.OUTPUT_FILENAME}}'
      UNIX_OUTPUT_PATH: '{{.HOME}}/.local/share/terraform/plugins/registry.terraform.io/provider/ceph/{{.PLUGIN_VERSION}}/{{OS}}_{{ARCH}}'
    cmds:
      - |
        {{if eq OS "windows"}}
          echo "Building and installing plugin in {{.WINDOWS_OUTPUT_PATH}}"
          go build -o "{{.WINDOWS_OUTPUT_PATH}}"
        {{else}}
          {{if eq OS "darwin"}}
            echo "Building and installing plugin in {{.DARWIN_OUTPUT_PATH}}"
            go build -o "{{.DARWIN_OUTPUT_PATH}}"
          {{else}}
            echo "Building and installing plugin in {{.UNIX_OUTPUT_PATH}}"
            task build
            mkdir -p "{{.UNIX_OUTPUT_PATH}}"
            \mv -f "{{.OUTPUT_FILENAME}}" "{{.UNIX_OUTPUT_PATH}}"
          {{end}}
        {{end}}
    silent: true
